### ISSUE TITLE
Missing parcel apis

### ISSUE THREAD

**Issue by upple** [flutter-tizen/tizen_interop#26]
Parcel API has been supported since Tizen 6.5.
However, it is not supported in `tizen_interop` even in version 7.0.
Would it be possible to add the parcel.h APIs? They are included in the `platform/core/base/bundle` repository.

**Comment by swift-kim** [comment]
Any link to Tizen Docs if it's a public API?

**Comment by upple** [comment]
The parcel.h APIs are internal, so interop support may only be available for public APIs.
I expected like as C# interop.
If you only plan to support Flutter interop for public APIs, then you may ignore this request.

**Comment by swift-kim** [comment]
Only public APIs are included in this package and we don't plan to add any internal APIs.

You can access internal APIs directly through Dart FFI in your app (at your own risk, as non-public APIs are subject to change without the ACR process). Dart FFI is very similar to C# PInvoke but has a few more limitations.

**Comment by upple** [comment]
@swift-kim 
Thank you for the detail description!
